// Enums para códigos de erro do Firebase
export enum FirebaseErrorCodes {
	// Erros de autenticação
	EMAIL_ALREADY_IN_USE = 'auth/email-already-in-use',
	INVALID_EMAIL = 'auth/invalid-email',
	INVALID_CREDENTIAL = 'auth/invalid-credential',
	WEAK_PASSWORD = 'auth/weak-password',
	USER_NOT_FOUND = 'auth/user-not-found',
	WRONG_PASSWORD = 'auth/wrong-password',
	TOO_MANY_REQUESTS = 'auth/too-many-requests',
	USER_DISABLED = 'auth/user-disabled',
	OPERATION_NOT_ALLOWED = 'auth/operation-not-allowed',
	ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL = 'auth/account-exists-with-different-credential',
	REQUIRES_RECENT_LOGIN = 'auth/requires-recent-login',
	CREDENTIAL_ALREADY_IN_USE = 'auth/credential-already-in-use',
	INVALID_VERIFICATION_CODE = 'auth/invalid-verification-code',
	INVALID_VERIFICATION_ID = 'auth/invalid-verification-id',
	MISSING_VERIFICATION_CODE = 'auth/missing-verification-code',
	QUOTA_EXCEEDED = 'auth/quota-exceeded',
	APP_NOT_AUTHORIZED = 'auth/app-not-authorized',
	INVALID_APP_CREDENTIAL = 'auth/invalid-app-credential',
	INVALID_USER_TOKEN = 'auth/invalid-user-token',
	USER_TOKEN_EXPIRED = 'auth/user-token-expired',
	NULL_USER = 'auth/null-user',
	INVALID_API_KEY = 'auth/invalid-api-key',
	INVALID_APP_ID = 'auth/invalid-app-id',
	INVALID_ARGUMENT = 'auth/invalid-argument',
	INVALID_CONTINUE_URI = 'auth/invalid-continue-uri',
	INVALID_CREATED_CREDENTIAL = 'auth/invalid-created-credential',
	INVALID_DISPLAY_NAME = 'auth/invalid-display-name',
	INVALID_LOGIN_CREDENTIALS = 'auth/invalid-login-credentials',
	INVALID_PERSISTENCE_TYPE = 'auth/invalid-persistence-type',
	INVALID_PHONE_NUMBER = 'auth/invalid-phone-number',
	INVALID_PROVIDER_DATA = 'auth/invalid-provider-data',
	INVALID_SESSION_INFO = 'auth/invalid-session-info',
	INVALID_TENANT_ID = 'auth/invalid-tenant-id',
	MISSING_ANDROID_PKG_NAME = 'auth/missing-android-pkg-name',
	MISSING_APP_CREDENTIAL = 'auth/missing-app-credential',
	MISSING_CLIENT_TYPE = 'auth/missing-client-type',
	MISSING_CONTINUE_URI = 'auth/missing-continue-uri',
	MISSING_IFRAME_START = 'auth/missing-iframe-start',
	MISSING_IOS_BUNDLE_ID = 'auth/missing-ios-bundle-id',
	MISSING_OR_INVALID_NONCE = 'auth/missing-or-invalid-nonce',
	MISSING_PHONE_NUMBER = 'auth/missing-phone-number',
	MISSING_VERIFICATION_ID = 'auth/missing-verification-id',
	PROVIDER_ALREADY_LINKED = 'auth/provider-already-linked',
	SESSION_EXPIRED = 'auth/session-expired',
	UNAUTHORIZED_DOMAIN = 'auth/unauthorized-domain',
	UNSUPPORTED_FIRST_FACTOR = 'auth/unsupported-first-factor',
	UNSUPPORTED_PERSISTENCE_TYPE = 'auth/unsupported-persistence-type',
	UNSUPPORTED_TENANT_OPERATION = 'auth/unsupported-tenant-operation',
	WEB_STORAGE_UNSUPPORTED = 'auth/web-storage-unsupported',
}

// Mensagens de erro português
export const FIREBASE_ERROR_MESSAGES = {
	[FirebaseErrorCodes.EMAIL_ALREADY_IN_USE]: 'Este email já está sendo usado por outra conta.',
	[FirebaseErrorCodes.INVALID_EMAIL]: 'Formato de email inválido. Verifique seu endereço de email.',
	[FirebaseErrorCodes.INVALID_CREDENTIAL]: 'Credenciais inválidas. Verifique seu email e senha.',
	[FirebaseErrorCodes.WEAK_PASSWORD]: 'Senha muito fraca. Use pelo menos 6 caracteres.',
	[FirebaseErrorCodes.USER_NOT_FOUND]: 'Usuário não encontrado. Verifique seu email ou crie uma conta.',
	[FirebaseErrorCodes.WRONG_PASSWORD]: 'Senha incorreta. Tente novamente.',
	[FirebaseErrorCodes.TOO_MANY_REQUESTS]: 'Muitas tentativas. Tente novamente mais tarde.',
	[FirebaseErrorCodes.USER_DISABLED]: 'Esta conta foi desabilitada.',
	[FirebaseErrorCodes.OPERATION_NOT_ALLOWED]: 'Esta operação não é permitida.',
	[FirebaseErrorCodes.ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL]: 'Uma conta já existe com este email usando um método de login diferente.',
	[FirebaseErrorCodes.REQUIRES_RECENT_LOGIN]: 'Esta operação requer um login recente. Faça login novamente.',
	[FirebaseErrorCodes.CREDENTIAL_ALREADY_IN_USE]: 'Esta credencial já está sendo usada por outra conta.',
	[FirebaseErrorCodes.INVALID_VERIFICATION_CODE]: 'Código de verificação inválido.',
	[FirebaseErrorCodes.INVALID_VERIFICATION_ID]: 'ID de verificação inválido.',
	[FirebaseErrorCodes.MISSING_VERIFICATION_CODE]: 'Código de verificação ausente.',
	[FirebaseErrorCodes.MISSING_VERIFICATION_ID]: 'ID de verificação ausente.',
	[FirebaseErrorCodes.QUOTA_EXCEEDED]: 'Cota excedida. Tente novamente mais tarde.',
	[FirebaseErrorCodes.APP_NOT_AUTHORIZED]: 'Aplicativo não autorizado.',
	[FirebaseErrorCodes.INVALID_APP_CREDENTIAL]: 'Credencial do aplicativo inválida.',
	[FirebaseErrorCodes.INVALID_USER_TOKEN]: 'Token do usuário inválido.',
	[FirebaseErrorCodes.USER_TOKEN_EXPIRED]: 'Token do usuário expirado.',
	[FirebaseErrorCodes.NULL_USER]: 'Usuário nulo.',
	[FirebaseErrorCodes.INVALID_API_KEY]: 'Chave da API inválida.',
	[FirebaseErrorCodes.INVALID_APP_ID]: 'ID do aplicativo inválido.',
	[FirebaseErrorCodes.INVALID_ARGUMENT]: 'Argumento inválido.',
	[FirebaseErrorCodes.INVALID_CONTINUE_URI]: 'URI de continuação inválido.',
	[FirebaseErrorCodes.INVALID_CREATED_CREDENTIAL]: 'Credencial criada inválida.',
	[FirebaseErrorCodes.INVALID_DISPLAY_NAME]: 'Nome de exibição inválido.',
	[FirebaseErrorCodes.INVALID_LOGIN_CREDENTIALS]: 'Credenciais de login inválidas.',
	[FirebaseErrorCodes.INVALID_PERSISTENCE_TYPE]: 'Tipo de persistência inválido.',
	[FirebaseErrorCodes.INVALID_PHONE_NUMBER]: 'Número de telefone inválido.',
	[FirebaseErrorCodes.INVALID_PROVIDER_DATA]: 'Dados do provedor inválidos.',
	[FirebaseErrorCodes.INVALID_SESSION_INFO]: 'Informações da sessão inválidas.',
	[FirebaseErrorCodes.INVALID_TENANT_ID]: 'ID do tenant inválido.',
	[FirebaseErrorCodes.MISSING_ANDROID_PKG_NAME]: 'Nome do pacote Android ausente.',
	[FirebaseErrorCodes.MISSING_APP_CREDENTIAL]: 'Credencial do aplicativo ausente.',
	[FirebaseErrorCodes.MISSING_CLIENT_TYPE]: 'Tipo de cliente ausente.',
	[FirebaseErrorCodes.MISSING_CONTINUE_URI]: 'URI de continuação ausente.',
	[FirebaseErrorCodes.MISSING_IFRAME_START]: 'Início do iframe ausente.',
	[FirebaseErrorCodes.MISSING_IOS_BUNDLE_ID]: 'ID do bundle iOS ausente.',
	[FirebaseErrorCodes.MISSING_OR_INVALID_NONCE]: 'Nonce ausente ou inválido.',
	[FirebaseErrorCodes.MISSING_PHONE_NUMBER]: 'Número de telefone ausente.',
	[FirebaseErrorCodes.PROVIDER_ALREADY_LINKED]: 'Provedor já vinculado.',
	[FirebaseErrorCodes.SESSION_EXPIRED]: 'Sessão expirada.',
	[FirebaseErrorCodes.UNAUTHORIZED_DOMAIN]: 'Domínio não autorizado.',
	[FirebaseErrorCodes.UNSUPPORTED_FIRST_FACTOR]: 'Primeiro fator não suportado.',
	[FirebaseErrorCodes.UNSUPPORTED_PERSISTENCE_TYPE]: 'Tipo de persistência não suportado.',
	[FirebaseErrorCodes.UNSUPPORTED_TENANT_OPERATION]: 'Operação de tenant não suportada.',
	[FirebaseErrorCodes.WEB_STORAGE_UNSUPPORTED]: 'Armazenamento web não suportado.',
};

// Função para obter mensagem de erro traduzida
export const getErrorMessage = (errorCode: string): string => {
	return FIREBASE_ERROR_MESSAGES[errorCode as FirebaseErrorCodes] || 'Ocorreu um erro inesperado. Tente novamente mais tarde.';
};

// Função para obter mensagem de sucesso
export const SUCCESS_MESSAGES = {
	SIGNUP_SUCCESS: 'Conta criada com sucesso! Verifique seu email.',
	SIGNIN_SUCCESS: 'Login realizado com sucesso!',
	SIGNOUT_SUCCESS: 'Logout realizado com sucesso!',
};
